PERIPHERALS_MAPPING = {
    "syscon_n94x": {"from": "mcxn947", "mapping": {"mcxn947": ["SYSCON"]}},
    "SYSCON_N54X": {"from": "mcxn547", "mapping": {"mcxn547": ["SYSCON"]}},
    "pint": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["PINT"]}},
    "INPUTMUX": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["INPUTMUX"]}},
    "CTIMER": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["CTIMER"]}},
    "FREQME": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["FREQME"]}},
    "UTICK": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["UTICK"]}},
    "MRT": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["MRT"]}},
    "WWDT": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["WWDT"]}},
    "CACHE64_CTRL": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["CACHE64_CTRL"]}},
    "CACHE64_POLSEL": {
        "from": "mcxn947",
        "mapping": {"mcxn[5|9]47": ["CACHE64_POLSEL"]},
    },
    "I3C": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["I3C"]}},
    "GDET": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["GDET"]}},
    "ITRC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["ITRC"]}},
    "PKC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["PKC"]}},
    "PUF": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["PUF"]}},
    "PUF_CTRL": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["PUF_CTRL"]}},
    "SM3": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SM3"]}},
    "BSP32": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["BSP32"]}},
    "SMARTDMA": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SMARTDMA"]}},
    "PLU": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["PLU"]}},
    "PORT": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["PORT"]}},
    "MSF1_B": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["MSF1_B"]}},
    "SCG": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SCG"]}},
    "SPC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SPC"]}},
    "WUU": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["WUU"]}},
    "CMC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["CMC"]}},
    "OSTIMER": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["OSTIMER"]}},
    "LPTMR": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["LPTMR"]}},
    "RTC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["RTC"]}},
    "RTC_SUBSYSTEM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["RTC_SUBSYSTEM"]}},
    "TSI": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["TSI"]}},
    "CMP": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["CMP"]}},
    "S50": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["S50"]}},
    "DIGTMP": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["DIGTMP"]}},
    "VBAT": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["VBAT"]}},
    "TRNG": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["TRNG"]}},
    "EIM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["EIM"]}},
    "ERM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["ERM"]}},
    "INTM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["INTM"]}},
    "DMA": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["DMA"]}},
    "DMA_TCD": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["DMA_TCD"]}},
    "SCT": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SCT"]}},
    "LPSPI": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["LPSPI"]}},
    "LPUART": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["LPUART"]}},
    "LP_FLEXCOMM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["LP_FLEXCOMM"]}},
    "LPI2C": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["LPI2C"]}},
    "GPIO": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["GPIO"]}},
    "SEMA42": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SEMA42"]}},
    "MAILBOX": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["MAILBOX"]}},
    "CDOG": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["CDOG"]}},
    "DM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["DM"]}},
    "POWERQUAD": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["POWERQUAD"]}},
    "EWM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["EWM"]}},
    "SYSPM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SYSPM"]}},
    "MBC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["MBC"]}},
    "FLEXSPI": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["FLEXSPI"]}},
    "OTPC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["OTPC"]}},
    "CRC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["CRC"]}},
    "NPX": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["NPX"]}},
    "PWM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["PWM"]}},
    "ENC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["ENC"]}},
    "EVTG": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["EVTG"]}},
    "CAN": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["CAN"]}},
    "USBDCD": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["USBDCD"]}},
    "USB_FS": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["USB_FS"]}},
    "ENET": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["ENET"]}},
    "EMVSIM": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["EMVSIM"]}},
    "FLEXIO": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["FLEXIO"]}},
    "SAI": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SAI"]}},
    "SINC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["SINC"]}},
    "USDHC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["USDHC"]}},
    "USBPHY": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["USBPHY"]}},
    "USBHSDCD": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["USBHSDCD"]}},
    "USBHS": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["USBHS"]}},
    "USBNC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["USBNC"]}},
    "MICFIL": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["MICFIL"]}},
    "ADC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["ADC"]}},
    "DAC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["DAC"]}},
    "OPAMP": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["OPAMP"]}},
    "VREF": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["VREF"]}},
    "HPDAC": {"from": "mcxn947", "mapping": {"mcxn[5|9]47": ["HPDAC"]}},
}

KEYWORDS = [
    "s",
    "abstract",
    "alignof",
    "as",
    "async",
    "await",
    "become",
    "box",
    "break",
    "const",
    "continue",
    "crate",
    "do",
    "else",
    "enum",
    "extern",
    "false",
    "final",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "macro",
    "match",
    "mod",
    "move",
    "mut",
    "offsetof",
    "override",
    "priv",
    "proc",
    "pub",
    "pure",
    "ref",
    "return",
    "self",
    "sizeof",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "try",
    "type",
    "typeof",
    "unsafe",
    "unsized",
    "use",
    "virtual",
    "where",
    "while",
    "yield",
    "set_bit",
    "clear_bi",
    "bit",
    "bits",
]
